param(
    [string]$CfmsRoot = "D:\NetdiskProject\CFMS_WebSocket\cfms_on_websocket",
    [ValidateSet("smoke", "pytest-basic", "pytest-all")]
    [string]$Mode = "smoke",
    [string]$ServerHost = "localhost",
    [int]$Port = 5104,
    [switch]$NoSsl
)

$ErrorActionPreference = "Stop"

$projectFile = Join-Path $CfmsRoot "pyproject.toml"
if (-not (Test-Path $projectFile)) {
    throw "CFMS project not found: $projectFile"
}

Push-Location $CfmsRoot
try {
    switch ($Mode) {
        "smoke" {
            $smokeScript = "D:\NetdiskProject\Netdisk\scripts\cfms\cfms_smoke_test.py"
            if (-not (Test-Path $smokeScript)) {
                throw "Smoke test script not found: $smokeScript"
            }

            $args = @("run", "--project", ".", "python", $smokeScript, "--host", $ServerHost, "--port", "$Port")
            if ($NoSsl) {
                $args += "--no-ssl"
            }
            # Use src/admin_password.txt generated by CFMS init
            $args += @("--admin-password-file", ".\src\admin_password.txt")
            & uv @args
        }
        "pytest-basic" {
            & uv run --project . pytest tests/test_basic.py -v
        }
        "pytest-all" {
            & uv run --project . pytest -v
        }
    }
}
finally {
    Pop-Location
}

